### ISSUE TITLE
ContentUnsupported Error

### ISSUE THREAD

**Issue by itz-kirankumar** [teticio/kindle2pdf#2]
C:\Windows\System32>kindle2pdf B0D6RJRT2Y
Book B0D6RJRT2Y is not available for dow
![image](https://github.com/user-attachments/assets/43d36e0f-35b7-410d-aa47-ae0125d58569)
nload (ContentUnsupported).

**Comment by teticio** [comment]
Are you able to read that in Kindle Cloud Reader (e.g., https://read.amazon.co.uk/?asin= B0D6RJRT2Y)? You need to have purchased the full book (not just the downloaded the sample).

**Comment by itz-kirankumar** [comment]
No , not a sample...purchased the full book

**Comment by teticio** [comment]
Please confirm what happens when you navigate to  https://read.amazon.co.uk/?asin=B0D6RJRT2Y . I get "The book you are trying to read can only be opened on the Kindle App" but then I don't own it. If you get the same message it confirms that this is a restriction from Amazon / the publisher.

**Comment by singlerider** [comment]
> Please confirm what happens when you navigate to https://read.amazon.co.uk/?asin=B0D6RJRT2Y . I get "The book you are trying to read can only be opened on the Kindle App" but then I don't own it. If you get the same message it confirms that this is a restriction from Amazon / the publisher.

I am seeing this on a purchased book from the <https://read.amazon.com/> e-reader, as well. The book works on the Kindle app, as one would expect form the message, 

![image](https://github.com/user-attachments/assets/a23c411e-ce27-49ac-a99f-e089d167f027)

'Just echoing the "issue" of not being able to download it using this tool. It would be great to have recommendations for other possible methods to extract the content.

**Comment by teticio** [comment]
Unfortunately, I have only reverse engineered the web application and some books like this one can only be opened in the mobile / desktop app. The same could potentially be done with the app, but I haven't got around to trying that. One would need to intercept the requests using Burp suite or similar. On Android, for example, you would need to patch the app to not pin certificates. It might be easier with the Windows Kindle app. I'll look into it sometime, but if someone else wants to have a crack at it...
