### ISSUE TITLE
Output is empty

### ISSUE THREAD

**Issue by cvlver** [teticio/kindle2pdf#3]
See attached, I've run the command but the output is empty. It's possible I don't know where the default output directory is. Please advise.

<img width="1025" alt="Screenshot 2024-08-18 at 8 24 18 AM" src="https://github.com/user-attachments/assets/71bbc76f-7a08-4039-91eb-3a4e3ad7a01e">
<img width="820" alt="Screenshot 2024-08-18 at 8 24 42 AM" src="https://github.com/user-attachments/assets/576c3073-899f-49c5-9840-d999cdc0744a">

**Comment by teticio** [comment]
As you can see there was an error. As mentioned in the README, you need to close Chrome before running the script (on Windows). Hope this fixes your issue but please let me know if not.

**Comment by teticio** [comment]
I can see it started to download the file "There is No Good Card For This" but it is zero bytes. Was there no progress bar?

**Comment by teticio** [comment]
It should output a .pdf file in the same directory where you run the script, with the name of the book.

**Comment by teticio** [comment]
Hmmmm, that is weird, so it downloaded the whole thing and created the "There is No Good card for This" file (which should be a PDF)  but it is zero bytes. A bit difficult for me to debug without being able to reproduce. It would greatly help me if you could add some debugging. I wonder if it is in a format that is not recognized and is not drawing anything in the PDF for some reason. To check this you could add this between lines 355 and 356 in the `kindle2pdf.py` script
`print(".")`
I would be very grateful if you were to try this and let me know if you see any dots being output.

**Comment by teticio** [comment]
Well the debugging shows that it is rendering stuff to the PDF, which is
exactly what I wanted to check but couldn't without buying the book :-). I
am really puzzled why it doesn't manage to save the file properly and I
can't really see how to help. I wonder if it is some permission
problem. ¯\_(ツ)_/¯

**Comment by eikaramba** [comment]
i have the same problem unfortunately. 
![grafik](https://github.com/user-attachments/assets/6174cb7d-34bd-41d9-833a-b5fa263de9e3)

rendering took some time, afterwards i had a empty file on disk

windows 10 here

**Comment by eikaramba** [comment]
btw due to this bug i needed to save the cookies locally and directly import them in the script from disk
https://github.com/borisbabic/browser_cookie3/issues/210

```
def read_cookies_from_file(file_path):
    cookie_jar = http.cookiejar.MozillaCookieJar()
    cookie_jar.load(file_path, ignore_discard=True, ignore_expires=True)
    cookies = {cookie.name: cookie.value for cookie in cookie_jar}
    return cookies
```

**Comment by eikaramba** [comment]
i found the issue. it was the output name. a : sign in the title prevented it from beeing saved. once i set the output name manually via argument it worked

**Comment by teticio** [comment]
Thank you! So obvious now you point it out (although an error message rather than an empty file would have been nice from Windows). I have added some code to sanitize the filename if no argument is provided.

Regarding your other point, hopefully this will get fixed soon in `browser_cookie3`, but thanks for the heads up.
