### ISSUE TITLE
Unable to get key for cookie decryption

### ISSUE THREAD

**Issue by jej-dev** [teticio/kindle2pdf#6]
Hello does anyone have any workarounds for the browser_cookie3.BrowserCookieError: Unable to get key for cookie decryption?

I don't know how to code so if anyone would be kind enough to give me a dumb down way it will be greatly appreciated.

**Comment by jej-dev** [comment]
I tried to provide additional information with --save-mock but the respomses.jsonl file came back to be completely empty.

I apologize for not having more information to provide.

**Comment by teticio** [comment]
This looks like an issue with browser cookie 3. Have you looked there?

**Comment by teticio** [comment]
I'm guessing you are running on a mac. "It works for me" but you could try with `sudo kindle2pdf ....`. You'd then have to do `sudo chown yourusername ...pdf` afterwards.

**Comment by teticio** [comment]
This appears to be an issue with the latest version of Chrome (Version 130.0.6723.58 (Official Build) (64-bit)) and browser-cookie3. It looks like ti will be fixed soon:
https://github.com/borisbabic/browser_cookie3/issues/210

**Comment by teticio** [comment]
I've change it to work with other browsers (not just Chrome), so you could always try logging in with Firefox, for example, until this issue is resolved.

**Comment by jej-dev** [comment]
I use Firefox on Ubuntu in WSL2 on Windows. It works for me now.
